### ISSUE TITLE
Roadmap to v1.0-beta

### ISSUE THREAD

**Issue by pixlcrashr** [TheMysteriousVincent/ArmA3URLFetch#12]
For the next version of ArmA3URLFetch there several feature unimplemented, such as:
 - ~~Result strings bigger than  10240 (means we need a function which returns only a part of a string) #14~~
 - Add a function documentation #13 

If there are other features left, we will add it here.

**Comment by TheMysteriousVincent** [comment]
This feature will be inserted with the next few commits.

**Comment by pixlcrashr** [comment]
Added "big" string support 1a5d6ab
