### ISSUE TITLE
HTTP_USER_AGENT is missing

### ISSUE THREAD

**Issue by nerdalertdk** [TheMysteriousVincent/ArmA3URLFetch#18]
Hi

First of thanks for urlfetch, works greate.

Curl don't send an HTTP_USER_AGENT string
this is normal best practice to send an HTTP_USER_AGENT with an program identificer.

If you add HTTP_USER_AGENT could you also add OS info, like linux/windows and version :)

would help but my c++ knowledge is not there yet

**Comment by pixlcrashr** [comment]
Well thats a good idea. Ideally we could set the `User-Agent` to (of course) the running os and second we could add some kind of `a3urlfetch` information.

**Comment by pixlcrashr** [comment]
Should be merged into it now.

**Comment by pixlcrashr** [comment]
Fixed with the last commits. Version header can now be edited within the file `macros.h`.
