### ISSUE TITLE
RvExtensionArgs Support.

### ISSUE THREAD

**Issue by Ragebone** [TheMysteriousVincent/ArmA3URLFetch#2]
## Theoretisch
Ist das egal

## Praktisch 
vereinfacht sich das Parsen von Daten innerhalb der Extension immens.

Der eigentliche Call wird etwas verständlicher.

Die Extension kann einen eigenen Fehler -Code zurück geben.
Debugging in Arma und stati der Extension können dadurch verbessert werden.

Gruß Rage

**Comment by pixlcrashr** [comment]
5197ee8cf61cada6f549bdc246ea77fbcf42001f switched to RVExtensionArgs support only.
