### ISSUE TITLE
Add headers to a3uf_common_fnc_addClient

### ISSUE THREAD

**Issue by nerdalertdk** [TheMysteriousVincent/ArmA3URLFetch#20]
Hi

Is there an easy way to use headers with `a3uf_common_fnc_request`
Our api uses an auth token in the header for validation and it would help for simplicity
in the sqf code if we could use  `a3uf_common_fnc_request` instead of `a3uf_common_fnc_setClientHeaders`/`a3uf_common_fnc_clientRequest`

Like so
```
private _response = [
    <string/url>, //the url of an request
    <string/method>, //the HTTP method; most of the time it is "GET"
    <array/params>, //(optional) parameters of the url request
    <array/headers>, //(optional) headers of the url request
    <bool/decodeJson> //(optional) should a json response converted?
] call a3uf_common_fnc_request;
```

**Comment by pixlcrashr** [comment]
Currently there is no such way to transmit HTTP headers via `a3uf_common_fnc_request` because there are technically only bad solutions available because of ArmA 3.

The only way to accomplish this idea is to use something like this format
```
["FUNC", ["#headers", "Header1=222", [...], "#url=https://example.com", "#parameter", "something=example", [...]]] callExtensions "arma3urlfetch";
```
to create some kind of list sequences in a one dimensional array.

**Comment by nerdalertdk** [comment]
this could work, wrap nicely in its own sqf function

but could you help me filling out the blacks.
```sqf
[
  "FUNC",
  [
    "#headers", "Header1=222", [_what_goes_here_],
    "#url=https://example.com",
    "#parameter", "something=example", [_what_goes_here_]
  ]
] callExtensions "arma3urlfetch";
```

**Comment by pixlcrashr** [comment]
The `[...]` just a meaning that you can add several header entries behind a `#headers` keyword.

Like this:
```sqf
[
    "FUNC", 
    [
        "#headers", "Header1=222", "Header2=3345", "Header3=testsd sdf sd qwe",
        "#url=https://example.com",
        "#parameter", "something=example", "parameter2=testparameter2"
    ]
] callExtensions "arma3urlfetch";
```

**Comment by nerdalertdk** [comment]
ahh got it, thanks :)

read [] as an array

**Comment by pixlcrashr** [comment]
This "issue" is not solved. It stays opened until we added this feature.

**Comment by pixlcrashr** [comment]
Alright then - within the last commits to 708ecb26ecdfbf62f8d134fec8c3ff67a88272f2 I added the ability to add headers to requests and clients.

Therefore currently there is just the ability to set whole client information in one request to "arma3urlfetch". Means that it is not possible anymore to update single parameters or headers.
