### ISSUE TITLE
GETRQ: 601 instead of 602?

### ISSUE THREAD

**Issue by Demellion** [TheMysteriousVincent/ArmA3URLFetch#22]
```C
21:07:28 ["",601,0]
21:07:28 ["",600,0]
21:07:28 ["",600,0]
21:07:28 ["",600,0]
21:07:28 ["",600,0]
21:07:28 ["",600,0]
21:07:28 ["",600,0]
21:07:28 ["",600,0]
21:07:29 ["",600,0]
21:07:29 ["",600,0]
21:07:29 ["",600,0]
```
This is a result of `GETRQ` code snippet in a cycle. Previous versions were reporting `602` code as intended to be that extension still going on with `SENDRQ`. Now it instantly falls to `601` which is `failed`.
Mistake? Thanks.

**Comment by pixlcrashr** [comment]
@Demellion Probably it is a mistake. Ill get into it later.
What parameters did you use to call the function(s)?

**Comment by pixlcrashr** [comment]
What version of A3URLFetch did you use?

**Comment by Demellion** [comment]
@TheMysteriousVincent It's a custom chain. Calls are:
```
...
private _query = "arma3urlfetch" callExtension [ 
	"SENDRQ", 
	[ 
		_url, 
		"#method=GET" 
	]
];
_query params ['_id','_httpcode'];
private _queryID = parseNumber _id;
waitUntil 
{ 
	uiSleep 0.1; 
	_query = "arma3urlfetch" callExtension [ 
		"GETRQ", 
		[ 
			_queryID
		] 
	];
...
```

**Comment by Demellion** [comment]
@TheMysteriousVincent Latest release.

**Comment by Demellion** [comment]
P.S Was using legacy 0.9 (i think) before it was fine. Now I can't return anything from `GET` request.

**Comment by pixlcrashr** [comment]
You just added the parameters wrong. It should be
```sqf
private _query = "arma3urlfetch" callExtension [ 
	"SENDRQ", 
	[ 
		"#url", _url, 
		"#method", "GET"
	]
];
```
instead of 
```sqf
private _query = "arma3urlfetch" callExtension [ 
	"SENDRQ", 
	[ 
		_url, 
		"#method=GET" 
	]
];
```
.
For instance, see the default function to make a stateless request: https://github.com/playnet-public/ArmA3URLFetch/blob/master/%40ArmA3URLFetch/addons/common/functions/fn_request.sqf#L29

I guess I just documented the changes of v1.0 just very bad.
But hey - this issue is a good annotation to documenting *things*.

This issue will stay opened until the changes of v1.0 were documented.

**Comment by Demellion** [comment]
@TheMysteriousVincent Thanks, will try out now.

**Comment by Demellion** [comment]
@TheMysteriousVincent According to linked function: works fine. I see the difference of calls now, thanks.
