### ISSUE TITLE
How to perform POST request?

### ISSUE THREAD

**Issue by fuxx** [TheMysteriousVincent/ArmA3URLFetch#23]
Hi Vincent,

first of all i really like the approach to use a http client to send my data to my backend instead of using extdb to connect my database directly. 

Right now i try to send some data to my backend but i am very new to SQF and i cant find a documentation how to make a manual post request to my backend. Maybe you have some advice what i am doing wrong here.

```
while {true} do {

	_serverName = serverName;
	_worldName = worldName;

	_justPlayers = allPlayers - entities "HeadlessClient_F";
	{
		_player = _x;
		_name = name _player;
		_uid = getPlayerUID _player;
		
		_uidParameter = format ["ping[arma_id]=%1", _uid];

		[
			"FUNC", 
			[
				"#url=https://x.x.royal-combat-force.de/x",
				"#method=POST",
				"#postData", _uidParameter
			]
	    ] callExtensions "arma3urlfetch";

	} forEach _justPlayers;
	Sleep 15;
};

```

 I want to send the player id to my backend as post, i always get an error that i am missing a ; near /ping (which is part of the URL. Maybe you can post a example for making a manual post request :)

From the RPT 
```
23:56:16 Error in expression <d=POST",
"#postData", _uidParameter
]
] callExtensions "arma3urlfetch";

} forEa>
23:56:16   Error position: <callExtensions "arma3urlfetch";

} forEa>
23:56:16   Error Missing ;
23:56:16 File rcf_custom\stats\pingpong.sqf, line 23
23:56:16 Error in expression <d=POST",
"#postData", _uidParameter
]
] callExtensions "arma3urlfetch";

} forEa>
23:56:16   Error position: <callExtensions "arma3urlfetch";

} forEa>
23:56:16   Error Missing ;
```
Greetings and thanks for the support,
Stefan

**Comment by fuxx** [comment]
I fixed the order of arguments now and renamed callExtensions to callExtension. No compile error anymore but i dont get any request on the server side. I am sure iam missing just one little thing :)

```
"arma3urlfetch" callExtension [
    "FUNC", 
    [
        "#url=https://x.x.royal-combat-force.de/x",
        "#method=POST",
        "#postData", _uidParameter
    ]
];
```

**Comment by pixlcrashr** [comment]
Well, you are not calling any available function. [See this list](https://github.com/playnet-public/ArmA3URLFetch/wiki/Commands) for available functions/commands.

You can also make a request with the predefined function (mentioned [here](https://github.com/playnet-public/ArmA3URLFetch/wiki/Usage)):
```sqf
private _response = [
    <string/url>, //the url of an request
    <string/method>, //the HTTP method; most of the time it is "GET"
    <array/headers>, //(optional) headers to send with the request
    <string,array/postData>, //(optional) the post data to send with the request
    <bool/decodeJson> //(optional) should a json response converted?
] call a3uf_common_fnc_request;
```
Please notice that this function is only available for scheduled scripts.

**Comment by fuxx** [comment]
Thank you very much :) I am very rookie to SQF so i used some code posted to another issue i found. I am using what you posted now and it works flawless :)

```
_uid = getPlayerUID _player;
_uidParameter = format ["ping[arma_id]=%1", _uid];
_response = [
	"https://x.x.royal-combat-force.de/x", //the url of an request
	"POST", //the HTTP method; most of the time it is "GET"
	["#postData", _uidParameter] //(optional) parameters of the url request
] call a3uf_common_fnc_request;
```

Thank you very much!
