### ISSUE TITLE
SENDRQ: 500 Internal Server Error [Windows]

### ISSUE THREAD

**Issue by Demellion** [TheMysteriousVincent/ArmA3URLFetch#31]
We met some reports with `SENDRQ` returning `500` code on first try, which tells that server is unable to process the condition. We did an experiment and used old version (1.0) of A3UF and it succeeded with the same conditions. It's a paradox, since tests shown that client and server confirmed not to be a source of a problem. Might that be a code exception related to 1.1 update in windows version?
Thanks.

**Comment by pixlcrashr** [comment]
Can you give me the test conditions used in your test? The error could be a different cause, because 5XX status codes are server errors.

**Comment by Demellion** [comment]
I'm trying to contact exacty person for details. Keep the issue open, I will close it myself if nothing going to happen. Thanks.

**Comment by Demellion** [comment]
The issue is not valid due to no report details.
Sorry for taking your time.
