### ISSUE TITLE
CPU Unexpected load.

### ISSUE THREAD

**Issue by Demellion** [TheMysteriousVincent/ArmA3URLFetch#32]
Windows servers running DLL with no players are experiencing some huge CPU loads (~30-40% average). This was tested on both desktop and server type of CPU's (i7-7700K and Xeon E5 1650-v4) but both servers were running Windows 2016 Standart. There are nothing else in common but 2016 OS, so that might be an issue source. Servers do not experience any load without DLL used.
Thanks.

**Comment by pixlcrashr** [comment]
@Demellion I experienced the same issue some time ago. I assume the while loop in the worker thread(s) is not that efficient as it could be.
I'll get into it later on.

**Comment by pixlcrashr** [comment]
Would you like to test the performance with this new artifact .dll's?:
https://ci.appveyor.com/api/buildjobs/fcs1hi75mwu8d6yp/artifacts/arma3urlfetch_x64.dll

Is the performance increased/decreased? Or is there no difference in performance?

**Comment by Demellion** [comment]
Will do ASAP.

EDIT 1: First people reporting CPU loads are not present anymore. Waiting for other reports.
EDIT 2: DLL does seem to be non-operational, thus obviously have no CPU impact. Extension is called and initialized but doesn't seem to return anything valid.

**Comment by Demellion** [comment]
Yes, its confirmed that this artifact has issues, it doesn't really return results from `GETRQ`

**Comment by pixlcrashr** [comment]
Alright. I thought of that issue as I committed the last changes.

But let me ask one more question: Are there any performance issues left?

**Comment by C0kkie** [comment]
Performance is fine with that.

**Comment by Demellion** [comment]
Well performance seems to be fine, but it's hard to tell if it wasn't around utilization coming from `GETRQ` result, since it doesn't return anything now - currently there might be no issues due to there is nothing to perform there.

**Comment by pixlcrashr** [comment]
So, I just created another artifact. You might want to test it: https://ci.appveyor.com/api/buildjobs/8oyjqvolen609r6q/artifacts/arma3urlfetch_x64.dll

I am waiting for your feedback.

**Comment by C0kkie** [comment]
For me works that now

**Comment by Leigham** [comment]
https://gyazo.com/2805f0b0e7e30dcae2d0c5edf4943850 not sure if you put some couts in there, but some random output to debug console.

**Comment by Demellion** [comment]
Tho couts are present - they do not interfere the output. That build is fine.
Thanks for cooperation.

**Comment by pixlcrashr** [comment]
reopened the issue because of the `cout`'s.

**Comment by pixlcrashr** [comment]
@Demellion @C0kkie @Leigham 

It is now recommended to use the latest release files:
https://github.com/playnet-public/ArmA3URLFetch/releases/tag/1.1.2
