### ISSUE TITLE
Any chance for an 64bit Linux version ?

### ISSUE THREAD

**Issue by Ni1kko** [TheMysteriousVincent/ArmA3URLFetch#33]
Any chance for an 64bit Linux version ?

**Comment by pixlcrashr** [comment]
Since the Linux ArmA 3 server is 32bit only, it does not make any sense to create a 64bit version for ArmA3URLFetch. Bootstrapping a 64bit shared library using a 32bit program is therefore not possible. If I am wrong, proof me.

**Comment by Ni1kko** [comment]
you are wrong lol for once i can say that  :p

https://i.imgur.com/eyBZMWJ.png
link to screenshot
https://dev.arma3.com/post/spotrep-00095

Or goto 
https://www.pcgamer.com/uk/after-seven-years-arma-3-hits-v20/
And
CTRL + F
`Added: 64-bit Linux Dedicated Server `
