### ISSUE TITLE
Arma 2.0 Update They Added Linux 64bit Support

### ISSUE THREAD

**Issue by Ni1kko** [TheMysteriousVincent/ArmA3URLFetch#34]
you are wrong lol for once i can say that  :p

https://i.imgur.com/eyBZMWJ.png
link to screenshot
https://dev.arma3.com/post/spotrep-00095

Or goto 
https://www.pcgamer.com/uk/after-seven-years-arma-3-hits-v20/
And
CTRL + F
`Added: 64-bit Linux Dedicated Server `

_Originally posted by @Ni1kko in https://github.com/playnet-public/ArmA3URLFetch/issues/33#issuecomment-721443962_

**Comment by pixlcrashr** [comment]
@Ni1kko Alright, got it. Thanks FYI. Since I am not into ArmA 3 that much anymore, I didn't follow their changelogs anymore.
I'll release a 64bit version today. Would be great if you then could tell me, if that version works then.

**Comment by Ni1kko** [comment]
Thanks and yeah no worries

**Comment by pixlcrashr** [comment]
There you go. The 64bit version:
[arma3urlfetch_x64.so.zip](https://github.com/playnet-public/ArmA3URLFetch/files/5486960/arma3urlfetch_x64.so.zip)

If it works I'll release it officially.

**Comment by Ni1kko** [comment]
Yes its working, But we still have to test it further but can confirm it loaded on x64 linux and we made a GET Request to our API and recieved our response... what all would you like us to test within it?

**Comment by pixlcrashr** [comment]
@Ni1kko Well, 'would be pretty neat if you test the binary over time regarding performance and possible memory leaks (there shouldn't be any difference, because I didn't modified the source code at all - but you can give it a shot).

**Comment by Ni1kko** [comment]
We are planing on making an api for our server and that is why we needed so have no issues with testing over a period of time and with different data ect, Thanks for taking time to update the project its really appreicated, im useless with cmake & makefile. i do everything within msvc (vs 2019).

**Comment by Ni1kko** [comment]
Can we add each other somewhere we can talk? i would like to ask a few things regarding building linux arma extensions.

**Comment by pixlcrashr** [comment]
ofc. Just add me on Discord: TheMysteriousVincent#0650

**Comment by Ni1kko** [comment]
Thanks, ill add you the now. ill messeage you when im home

**Comment by Ni1kko** [comment]
2 years no issues, POG

**Comment by pixlcrashr** [comment]
> 2 years no issues, POG

No issues in the sense that you had no issues with that extension over 2 years?
