### ISSUE TITLE
Error Generic Error in expression

### ISSUE THREAD

**Issue by lmarschall** [TheMysteriousVincent/ArmA3URLFetch#35]
Hey,

today i wanted to test your addon for my multiplayer mission, unfortunately, it doesn't work yet.

There's my example code: "_response = ["https://jsonplaceholder.typicode.com/posts/1", "GET"] call a3uf_common_fnc_request;"

This is the current error: 
![arma_3_url_fetch_error](https://user-images.githubusercontent.com/1447571/100480466-a0ebed80-30f1-11eb-8108-dccafbf8c03f.PNG)

**Comment by pixlcrashr** [comment]
Does this error also occur when using the following resource: `http://httpbin.org/get` ? You may try it, as I am currently busy. I try to fix the issue next week (if it is an issue).

**Comment by lmarschall** [comment]
seems not to work either... no worries its just for testing at the moment.

**Comment by lmarschall** [comment]
error was on my side... i could have thought about using spawn to call my function earlier...
