### ISSUE TITLE
ParseSimpleArray in Arma Support

### ISSUE THREAD

**Issue by Ragebone** [TheMysteriousVincent/ArmA3URLFetch#4]
## Aktuelles JSON parsing
passiert vollends in Arma.

Funktionieren tut das mit Sicherheit gut, Performance ist allerdings fragwürdig.

Seit einiger Zeit gibt es den Befehl
**ParseSimpleArray**
Der mehrdimensionale Arrays aus einem String Parsen kann.

M.m nach ist das der aktuellen SQF Implementierung vor zu ziehen.

Vorallem weil JSON Arrays identisch zu Arma Arrays sind.

Gruß Rage

**Comment by pixlcrashr** [comment]
@Ragebone Nicht wirklich. JSON Arrays umfassen auch Objekte mit `{`, `}` Klammern. Das tun ArmA 3 Arrays nicht.
Bsp.:
```json
[
    {
        "param2": false
    },
    {
        "param2": 1
    }
]
```
Es soll ja einen möglichst großen Umfang geben.
Allerdings könnte man `parseSimpleArray` nutzen, solange keine `{`, `}` Klammern in einem Resultat existieren.

**Comment by Ragebone** [comment]
@TheMysteriousVincent

Das ist vollkommen korrekt.

Nur ist der gemeinsame Nenner Arma.
Irgendwie musst du als Entwickler an die Daten kommen.
Und genau da sind die Möglichkeiten limitiert.

Wenn die Konversation von {} auf [] eh irgendwo irgendwann passieren muss, warum dann nicht in der Extension oder sogar in der API?

Je mehr aus Arma entfernt werden kann, desto besser läuft es.

Und sorry das ich aktuell auf Deutsch schreibe, bin da iwi rein gefallen.
Normalerweise halte ich mich an Englisch auf Github.

**Comment by pixlcrashr** [comment]
@Ragebone Wie schon gesagt: Letztendlich kann am Ende jeder selbst entscheiden, was er nutzen möchte. Ich präferiere da eher Objekte, da man diese sehr schön auch abseits in Java- und TypeScript nutzen kann^^. Man kann es aber API-technisch auch mit einem weiteren Parameter möglich machen, nur Arrays zurück zu geben.

**Comment by pixlcrashr** [comment]
5197ee8cf61cada6f549bdc246ea77fbcf42001f closed, because JSON decoding is now part of the extension. For more information watch the wiki.

**Comment by TheFireRunner** [comment]
Hello ^^
I have the same problem as @Ragebone . If the gear loadout is loaded then the CPU is at 40%. Without the gearloadout at 10%.

**Comment by pixlcrashr** [comment]
@TheFireRunner Which version did you use?

**Comment by TheFireRunner** [comment]
@TheMysteriousVincent Im using the newiest version: 1.1.2

EDIT: Ok the reason why the CPU from my Server is so high, is why the mission.sqm is too big xd
