### ISSUE TITLE
-debugCallExtension security and obscurity implications

### ISSUE THREAD

**Issue by Ragebone** [TheMysteriousVincent/ArmA3URLFetch#5]
In case of a **client-side deployment**, this parameter prohibits security through obscurity.

Affected are for example API tokens.

Basically everything a client would need, but shouldn't see or know himself that gets send to or through the extension.

Sincerely Rage

**Comment by pixlcrashr** [comment]
@Ragebone Such obscurity is possible in higher language's like C++, but its not worth the effort in SQF because there are too many security gaps.

**Comment by Ragebone** [comment]
obscurity of your extension does not exist because opensource.

what I mean is, if you have this deployed on all your clients, you want two things.

- to be sure that all API requests come from actual players playing right now.

- to be sure that API request from player1 is actually from player1.

solutions for that are API tokens, passwords, some magic sauce that has to be transmitted to the extension at some point to keep it away from player side SQF code.

The only thing you can count on, is that your extension is actually your extension and that it is unmodified, once you have it whitelisted by BE.

Securest place for such information was the extension. Until that command happened.

Possible attack scenario.

I snoop all extension calls. Through that I get all the info that I need to talk to your API.

And I can do all the things now. Depending on how your API is build, that can be very bad.

Not as bad as I thought, I admit that, but still not as awesome.

Sincerely Rage

**Comment by pixlcrashr** [comment]
@Ragebone It is planned (but not listed as issue ^^) that I or "We" behind the project will ask battleye for a whitelisting of this mod.
But why should you send and receive vulnerable data by the client? I think that would bad at all.

> some magic sauce that has to be transmitted to the extension at some point to keep it away from player side SQF code.

Do you mean that the extension(s) of the client(s) need an outside server for receiving an key or whatever?
That is maybe not the best idea.

The thing is: Why should vulnerable data be executed by the client? Client side API's in general are more used in things like requesting some unimportant text.

Important requests should be executed by the server.

**Comment by pixlcrashr** [comment]
@Ragebone You could create some kind of session-keys in the API and send an individual key to every new connected client - but no matter what you are trying to do as an workaround for denying requests in simple internet browsers, you could replicate every request of the client.

Or the last thing is to create some specific keys for every single "vulnerable request" that can be executed by the client. But there is a way to modify the outgoing request.

**Comment by pixlcrashr** [comment]
Are there any more comments?

**Comment by Ragebone** [comment]
@TheMysteriousVincent  no further questions and comments, except that Arma s output does only contain the function argument when using the new syntax.

... callExtension ["function", ["hello World"]];
Does print  something like:
"... called Estension .... [function]".

So as long as BIS doesn't change that, we can still transmit "secret" stuff to the extension.

**Comment by pixlcrashr** [comment]
@Ragebone The new syntax is already used in further version's than 0.7.*
But it is not the task of ArmA3URLFetch, to make, for exmaple, API security and their usage more safety.

**Comment by HJFinch** [comment]
@Ragebone security on the client side should always be ensured by api-side auth.
Meaning a standard logging (or passwordless-auth) which then returns a token for further use.
This login then might be verified on the server side by deprecating tokens of disconnected players and then propagating this to some kind of auth proxy.

Meaning, verifying the player/user is always required by the "user" (dev) and not the extension itself.
And obscurity is never a solution, neither are hardcoded secrets etc. It is not to hard, to secure this with a little experience of building api's and some mixing of server and client side functions.

But I'm happy to discuss this further if you like to (voice too).

**Comment by pixlcrashr** [comment]
#deprecated
